#define BORDER_WIDTH_INACTIVE 1
#define BORDER_WIDTH_ACTIVE 3
#define BORDER_COLOR_INACTIVE "rgb:2d/2b/40"
#define BORDER_COLOR_ACTIVE "rgb:6c/5c/e7"
#define BG_COLOR 0xdfe6e9

#define STATUS_BAR_HEIGHT 26
#define STATUS_BAR_BORDER_WIDTH 1
#define STATUS_BAR_BORDER_COLOR 0x000000
#define STATUS_BAR_BG_COLOR 0xffffff

#define MIN_WINDOW_WIDTH 100
#define MIN_WINDOW_HEIGHT 100