#define BORDER_WIDTH_INACTIVE 1
#define BORDER_WIDTH_ACTIVE 3
#define BORDER_COLOR_INACTIVE 0x2d2b40
#define BORDER_COLOR_INACTIVE_STR "rgb:2d/2b/40"
#define BORDER_COLOR_ACTIVE 0x6c5ce7
#define BORDER_COLOR_ACTIVE_STR "rgb:6c/5c/e7"
#define BG_COLOR 0xdfe6e9